routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\OrdersController;
use Illuminate\Support\Facades\Route;

// Home
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

// Login
Route::get('login', [App\Http\Controllers\LoginController::class, 'index']);
Route::post('login', [App\Http\Controllers\LoginController::class, 'login']);
Route::get('logout', [App\Http\Controllers\LoginController::class, 'logout']);
// Admin
Route::group(['namespace' => 'Admin'], function () {
    Route::get('admin', [HomeController::class, 'index']);
    // Product
    Route::resource('product', '\App\Http\Controllers\Admin\ProductController', [
        'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
    ]);
    // Slide_image
    Route::resource('slide', '\App\Http\Controllers\Admin\SlideImageController', [
        'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
    ]);
    // Oder
    Route::resource('orders', '\App\Http\Controllers\Admin\OrdersController', [
        'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
    ]);
    Route::post('update-status', [OrdersController::class, 'update_status']);
    // News
    Route::resource('news', '\App\Http\Controllers\Admin\NewsController', [
        'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
    ]);
});


// Product view
Route::get('/product-show/{url}', [App\Http\Controllers\HomeController::class, 'product_detail']);

// search category
Route::get('/product-category/{url}', [App\Http\Controllers\HomeController::class, 'product_category']);

//search all
Route::get('/product-search', [App\Http\Controllers\HomeController::class, 'product_search']);

// display cart
Route::get('/cart-display', [App\Http\Controllers\HomeController::class, 'display_cart']);

// pay
Route::get('pay', [App\Http\Controllers\HomeController::class, 'pay']);
// payment methods
Route::get('payment-methods', [App\Http\Controllers\HomeController::class, 'payment_methods']);
// store pay
Route::post('pay', [App\Http\Controllers\HomeController::class, 'store_pay']);

//introduce
Route::get('/introduce', [App\Http\Controllers\HomeController::class, 'introduce']);

//news
Route::get('/page-news', [App\Http\Controllers\HomeController::class, 'news']);

// details news
Route::get('/details-news/{url}', [App\Http\Controllers\HomeController::class, 'details_news']);

// contact
Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact']);



// return policy
Route::get('/return-policy', [App\Http\Controllers\HomeController::class, 'return_policy']);

Route::get('vn-pay', [App\Http\Controllers\HomeController::class, 'vn_pay']);
Route::post('vnpay-create-payment', [App\Http\Controllers\HomeController::class, 'vnpay_create_payment']);
Route::get('vnpay-return', [App\Http\Controllers\HomeController::class, 'vnpay_return']);

resources/views/admin_slide_image/slide_image.blade.php
@extends('layouts_admin.master')
@section('content')
    <div id="home-slide" class="container-fluid">
        <div class="title mb-2">
            <h4>Danh sách slide ảnh</h4>
            <div class="btn-create-slide">
                <a href="/slide/create" class="btn btn-primary">
                    Tạo sản phẩm mới
                </a>
            </div>
        </div>
        <div>
            @if(Session::has('message'))
                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{!! Session::get('message') !!}</p>
            @endif
        </div>
        <div>
            <form class="row mb-2" action="">
                <div class="col-md-2">
                    <label for="">Tên slide</label>
                    <input type="text" name="name" value="{{isset($_GET['name']) ? $_GET['name'] : ''}}"
                           class="form-control form-control-sm">
                </div>
                <div class="col-md-2">
                    <label for="">Danh mục sản phẩm</label>
                    <select name="category" class="form-control">
                        <option value="">Tất cả</option>
                        @foreach($products as $key => $value)
                            <option
                                value="{{$key}}" {{isset($_GET['category']) && $_GET['category'] == $key ? 'selected' : ''}}>{{$value}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-2">
                    <label for="">Công khai</label>
                    <select name="publish" class="form-control">
                        <option value="">Tất cả</option>
                        <option value="1" {{isset($_GET['publish']) && $_GET['publish'] == 1 ? 'selected' : ''}}>Có</option>
                        <option value="0" {{isset($_GET['publish']) && $_GET['publish'] == 0 ? 'selected' : ''}}>Không</option>
                    </select>
                </div>
                <div class="col-md-2">
                    <label for="">Ngày tạo từ</label>
                    <input type="date" class="form-control form-control-sm" name="date_from"
                           value="{{isset($_GET['date_from']) ? $_GET['date_from'] : ''}}">
                </div>
                <div class="col-md-2">
                    <label for="">Ngày tạo đến</label>
                    <input type="date" class="form-control form-control-sm" name="date_to"
                           value="{{isset($_GET['date_to']) ? $_GET['date_to'] : ''}}">
                </div>
                <div class="col-md-2">
                    <label class="w-100" for="" style="opacity: 0">Tìm kiếm</label>
                    <button type="submit" class="btn btn-primary w-100">Tìm kiếm</button>
                </div>
            </form>
        </div>
        <div class="row  mt-3">
            <div class="col-sm-3">
                <h4>
                    Tổng: {{$total_slide->total_slide}} quảng cáo
                </h4>
            </div>
            <div class="col-sm-3">
                <h4>
                    Chưa sử dụng: {{$slide_not_displayed->slide_not_displayed}} quảng cáo
                </h4>
            </div>
        </div>
        <div class="table-responsive-sm">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>Hình ảnh slide</th>
                    <th>Tên slide</th>
                    <th>Danh mục sản phẩm</th>
                    <th>Trạng thái</th>
                    <th>Ngày tạo</th>
                    <th>Ngày cập nhập</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($slide_image as $key => $value)
                    <tr>
                        <td>{{($key + 1)}}</td>
                        <td class="img_product">
                            <img src="{{isset($value->link_image) ? $value->link_image : ''}}" alt="">
                        </td>
                        <td>{{$value->name}}</td>
                        <td>{{$products[$value->product_id]}}</td>
                        <td class="text-center">{{$value->publish ? '✓' : ''}}</td>
                        <td>{{date('d-m-Y H:i:s', strtotime($value->created_at))}}</td>
                        <td>{{date('d-m-Y H:i:s', strtotime($value->update_at))}}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" href="/slide/{{$value->id}}/edit"><i
                                    class="far fa-edit"></i> Sửa</a>
                        </td>
                        <td>
                            <form action="{{ url('/slide', ['id' => $value->id]) }}" method="post"
                                  onsubmit="return confirm('Bạn chắc chắn muốn xóa sản phẩm này không?');">
                                {!! method_field('delete') !!}
                                {!! csrf_field() !!}
                                <button type="submit" class="btn btn-sm btn-danger"><i class="far fa-trash-alt"></i> Xóa
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div>
            @include('pagination.default_2', ['paginator' => $slide_image])
        </div>
    </div>

@stop

resources/views/admin_slide_image/slide_image_form.blade.php
@extends('layouts_admin.master')
@section('content')
    <div id="creat-slide" class="container-fluid mt-3">
        <h4>THÔNG TIN CHUNG</h4>
        <div>
            @if(Session::has('message'))
                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{!! Session::get('message') !!}</p>
            @endif
        </div>
        <form action="{{isset($slide_image) ? '/slide/' . $slide_image->id : route('slide.store')}}" method="POST"  enctype="multipart/form-data">
            @csrf
            @if (isset($slide_image))
                {{ method_field('PUT') }}
                <input type="hidden" name="id" value="{{$slide_image->id}}">
            @endif
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group row">
                        <label for="name" class="col-sm-4 col-form-label">
                            Tên slide
                            <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8">
                            <input name="name" id="name" type="text"
                                   value="{{ old('name', isset($slide_image->name) ? $slide_image->name : '') }}"
                                   class="form-control" required maxlength="250">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="product" class="col-sm-4 col-form-label">
                            Sản phẩm
                            <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8">
                            <select name="product_id" id="product" class="form-control" required>
                                <option value="">Chọn sản phẩm</option>
                                @foreach($products as $key => $value)
                                    <option
                                        value="{{$key}}" {{old('products') == $key || (isset($slide_image) && $slide_image->product_id == $key) ? 'selected' : ''}}>{{$value}}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Công khai</label>
                        <div class="col-sm-8">
                            <input type="hidden" name="publish" value="0">
                            <input id="publish" name="publish" type="checkbox"
                                   value="1" {{ !!old('publish') || (isset($slide_image->publish) && !!$slide_image->publish) ? 'checked="checked"' : '' }}>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">
                            Ảnh slide
                            <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8">
                            <div class="row">
                                @if(isset($slide_image->link_image))
                                        <div class="col-md-3 mb-2 img_product1">
                                            <img src="{{asset($slide_image->link_image)}}" alt="">
                                        </div>
                                @endif
                            </div>
                            <input class="mb-2" type="file" name="photos" multiple>
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary w-25">Xác nhận</button>
            </div>
        </form>
    </div>
@stop