routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\OrdersController;
use Illuminate\Support\Facades\Route;

// Home
Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

// Login
Route::get('login', [App\Http\Controllers\LoginController::class, 'index']);
Route::post('login', [App\Http\Controllers\LoginController::class, 'login']);
Route::get('logout', [App\Http\Controllers\LoginController::class, 'logout']);
// Admin
Route::group(['namespace' => 'Admin'], function () {
    Route::get('admin', [HomeController::class, 'index']);
    // Product
    Route::resource('product', '\App\Http\Controllers\Admin\ProductController', [
        'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
    ]);
    // Slide_image
    Route::resource('slide', '\App\Http\Controllers\Admin\SlideImageController', [
        'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
    ]);
    // Oder
    Route::resource('orders', '\App\Http\Controllers\Admin\OrdersController', [
        'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
    ]);
    Route::post('update-status', [OrdersController::class, 'update_status']);
    // News
    Route::resource('news', '\App\Http\Controllers\Admin\NewsController', [
        'only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']
    ]);
});


// Product view
Route::get('/product-show/{url}', [App\Http\Controllers\HomeController::class, 'product_detail']);

// search category
Route::get('/product-category/{url}', [App\Http\Controllers\HomeController::class, 'product_category']);

//search all
Route::get('/product-search', [App\Http\Controllers\HomeController::class, 'product_search']);

// display cart
Route::get('/cart-display', [App\Http\Controllers\HomeController::class, 'display_cart']);

// pay
Route::get('pay', [App\Http\Controllers\HomeController::class, 'pay']);
// payment methods
Route::get('payment-methods', [App\Http\Controllers\HomeController::class, 'payment_methods']);
// store pay
Route::post('pay', [App\Http\Controllers\HomeController::class, 'store_pay']);

//introduce
Route::get('/introduce', [App\Http\Controllers\HomeController::class, 'introduce']);

//news
Route::get('/page-news', [App\Http\Controllers\HomeController::class, 'news']);

// details news
Route::get('/details-news/{url}', [App\Http\Controllers\HomeController::class, 'details_news']);

// contact
Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact']);



// return policy
Route::get('/return-policy', [App\Http\Controllers\HomeController::class, 'return_policy']);

Route::get('vn-pay', [App\Http\Controllers\HomeController::class, 'vn_pay']);
Route::post('vnpay-create-payment', [App\Http\Controllers\HomeController::class, 'vnpay_create_payment']);
Route::get('vnpay-return', [App\Http\Controllers\HomeController::class, 'vnpay_return']);

resources/views/admin_order/order.blade.php
@extends('layouts_admin.master')
@section('content')
    <div id="home-oder" class="container-fluid">
        <div class="title mb-2">
            <h4>Danh sách đơn hàng</h4>
            <div class="btn-create-products">
                <a href="/orders/create" class="creat btn btn-primary">
                    Tạo sản phẩm mới
                </a>
            </div>
        </div>
        @if(Session::has('message'))
            <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{!! Session::get('message') !!}</p>
        @endif
        <div>
            <form class="row mb-2" action="">
                <div class="col-md-2">
                    <label for="code_orders">Mã đơn hàng</label>
                    <input type="text" name="code_orders" id="code_orders"
                           value="{{isset($_GET['code_orders']) ? $_GET['code_orders'] : ''}}"
                           class="form-control form-control-sm">
                </div>
                <div class="col-md-2">
                    <label for="full_name">Họ và tên</label>
                    <input type="text" name="full_name" id="full_name"
                           value="{{isset($_GET['full_name']) ? $_GET['full_name'] : ''}}"
                           class="form-control form-control-sm">
                </div>
                <div class="col-md-2">
                    <label for="phone_number">Số điện thoại</label>
                    <input type="number" name="phone_number" id="phone_number"
                           value="{{isset($_GET['phone_number']) ? $_GET['phone_number'] : ''}}"
                           class="form-control form-control-sm">
                </div>
                <div class="col-md-2">
                    <label for="address">Địa chỉ</label>
                    <input type="text" name="address" id="address"
                           value="{{isset($_GET['address']) ? $_GET['address'] : ''}}"
                           class="form-control form-control-sm">
                </div>
                <div class="col-md-2">
                    <label for="status">Trạng thái</label>
                    <select name="status" id="status" class="form-control">
                        <option value="">Tất cả</option>
                        @foreach($orders_status_name as $key => $value)
                            <option
                                value="{{$key}}" {{isset($_GET['status']) && $_GET['status'] == $key ? 'selected' : ''}}>{{$value}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-md-2">
                    <label for="date_from">Ngày tạo từ</label>
                    <input type="date" class="form-control form-control-sm" name="date_from" id="date_from"
                           value="{{isset($_GET['date_from']) ? $_GET['date_from'] : ''}}">
                </div>
                <div class="col-md-2">
                    <label for="date_to">Ngày tạo đến</label>
                    <input type="date" class="form-control form-control-sm" name="date_to" id="date_to"
                           value="{{isset($_GET['date_to']) ? $_GET['date_to'] : ''}}">
                </div>
                <div class="col-md-2">
                    <label class="w-100" for="" style="opacity: 0">Tìm kiếm</label>
                    <button type="submit" class="btn btn-primary w-100">Tìm kiếm</button>
                </div>
            </form>
        </div>
        <div class="row  mt-3">
            <div class="col-sm-3">
                <h4>
                    Tổng: {{$total_orders->total_orders}} đơn hàng
                </h4>
            </div>
            <div class="col-sm-4">
                <h4>
                    Đơn hàng đã hoàn thành: {{$orders_completed_order->orders_completed_order}} đơn hàng
                </h4>
            </div>
            <div class="col-sm-5">
                <h4>
                    Tổng tiền sản phẩm đã bán được: {{number_format($total_order_amount->total_order_amount)}} VND
                </h4>
            </div>
        </div>

        <div class="table-responsive-sm">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>Mã đơn hàng</th>
                    <th>Họ và tên</th>
                    <th>Số điện thoại</th>
                    <th>Địa chỉ</th>
                    <th>Ghi chú</th>
                    <th style="width: 161px;">Trạng thái</th>
                    <th>Lí do hủy</th>
                    <th>Ngày tạo</th>
                    <th>Ngày cập nhập</th>
                    <th style="width: 80px"></th>
                    <th style="width: 80px"></th>
                </tr>
                </thead>
                <tbody>
                @foreach($orders as $key => $value)
                    <tr>
                        <td>{{$key+1}}</td>
                        <td>{{$value->code_orders}}</td>
                        <td>{{$value->full_name}}</td>
                        <td>{{$value->phone_number}}</td>
                        <td>{{$value->address}}</td>
                        <td>{{$value->note}}</td>
                        <td>{{$orders_status_name[$value->order_status_id]}}</td>
                        <td>{{$value->cancellation_reason}}</td>
{{--                        <td>{{isset($orders_status_name[$value->order_status_id]) ? $orders_status_name[$value->order_status_id] : 'Chờ'}}</td>--}}

{{--                        @if($value->order_status_id == 5 )--}}
{{--                            <td>--}}
{{--                                {{$orders_status_name[$value->order_status_id]}}--}}
{{--                            </td>--}}
{{--                            <td></td>--}}
{{--                        @else--}}
{{--                            <td >--}}
{{--                                <select class="select form-control-sm" style="width: 75px;" orders_id="{{$value->id}}">--}}
{{--                                    @foreach($orders_status as $key => $item)--}}
{{--                                        @if($key + 1 == $value->order_status_id || $key == $value->order_status_id || $key == 5)--}}
{{--                                            <option class="status" value="{{$key+1}}"  >--}}
{{--                                                {{$item->status}}--}}
{{--                                            </option>--}}
{{--                                        @endif--}}
{{--                                    @endforeach--}}
{{--                                </select>--}}
{{--                                <button type="submit" class="update_btn btn-sm btn-primary w-80" >--}}
{{--                                    <i class="fas fa-upload "></i> Sửa--}}
{{--                                </button>--}}
{{--                            </td>--}}
{{--                            <td>--}}
{{--                                <input type="text" class="cancellation_reason form-control-sm" input_orders_id="{{$value->id}}" value="" disabled>--}}
{{--                            </td>--}}
{{--                        @endif--}}

                        <td>{{date('d-m-Y H:i:s', strtotime($value->created_at))}}</td>
                        <td>{{date('d-m-Y H:i:s', strtotime($value->update_at))}}</td>
                        <td style="white-space: nowrap">
                            <a class="btn btn-sm btn-primary" href="/orders/{{$value->id}}/edit"><i
                                    class="far fa-edit"></i> Sửa</a>
                        </td>
                        <td>
                            <form action="{{ url('/orders', ['id' => $value->id]) }}" method="post" onsubmit="return confirm('Bạn chắc chắn muốn xóa sản phẩm này không?');">
                                {!! method_field('delete') !!}
                                {!! csrf_field() !!}
                                <button type="submit" class="btn btn-sm btn-danger"><i class="far fa-trash-alt"></i> Xóa</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div>
            @include('pagination.default_2', ['paginator' => $orders])
        </div>
    </div>

@stop

resources/views/admin_order/order_form.blade.php
@extends('layouts_admin.master')
@section('content')
    <div id="creat-oder" class="container-fluid">
        <h4>Thông tin giao hàng</h4>
        <div>
            @if(Session::has('message'))
                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{!! Session::get('message') !!}</p>
            @endif
        </div>

        <form action="{{ isset($orders) ? '/orders/' . $orders->id  : route('orders.store') }}" method="POST"  enctype="multipart/form-data">
            @csrf
            @if (isset($orders))
                {{ method_field('PUT') }}
                <input type="hidden" name="id" value="{{$orders->id}}">
            @endif
            <div class="row">
                <div class="col-md-7" style="background-color: white">
                    <div class="form-group row">
                        <label for="full_name" class="col-sm-4 col-form-label">
                            Họ và tên
                            <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8">
                            <input name="full_name" id="full_name" type="text"
                                   value="{{ isset($orders->full_name) ? $orders->full_name : '' }}"
                                   class="form-control" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="phone_number" class="col-sm-4 col-form-label">
                            Số điện thoại
                            <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8">
                            <input name="phone_number" id="phone_number" type="number"
                                   value="{{ isset($orders->phone_number) ? $orders->phone_number : '' }}"
                                   class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="address" class="col-sm-4 col-form-label">
                            Địa chỉ
                            <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8">
                            <input name="address" id="address" type="text"
                                   value="{{ isset($orders->address) ? $orders->address : '' }}"
                                   class="form-control" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="note" class="col-sm-4 col-form-label">
                            Ghi chú
                            <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8">
                            <input name="note" id="note" type="text"
                                   value="{{ isset($orders->note) ? $orders->note : '' }}"
                                   class="form-control" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="status" class="col-sm-4 col-form-label">Trạng thái<span
                                class="text-danger">*</span></label>
                        <div class="col-sm-8">
                            <select name="order_status_id" id="status" class="form-control" required>
                                <option value="">Chọn danh mục</option>
                                @foreach($orders_status_name as $key => $value)
                                    <option
                                        value="{{$key}}" {{old('order_status_id') == $key || (isset($orders) && $orders->order_status_id == $key) ? 'selected' : ''}}>{{$value}}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="reason" class="col-sm-4 col-form-label">
                            Lí do hủy
                            <span class="text-danger"></span>
                        </label>
                        @if((isset($orders) && $orders->order_status_id == '6'))
                            <div class="col-sm-8">
                                <input name="cancellation_reason" id="reason" type="text"
                                       value="{{ isset($orders->cancellation_reason) ? $orders->cancellation_reason : '' }}"
                                       class="form-control" >
                            </div>
                        @else
                            <div class="col-sm-8">
                                <input name="cancellation_reason" id="reason" type="text"
                                       value="{{ isset($orders->cancellation_reason) ? $orders->cancellation_reason : '' }}"
                                       class="form-control" disabled>
                            </div>
                        @endif
                    </div>
                    <div class="text-lg-right">
                        <button type="submit" class="btn btn-primary pr-5 pl-5">Xác nhận</button>
                    </div>
                </div>

                <div class="col-md-5">
                    <div>
                        <table class="table">
                            <thead>
                            <tr class="text-center">
                                <th>Tên sản phẩm</th>
                                <th>Số lượng</th>
                                <th>Giá tiền</th>
                                <th>Tổng tiền</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(isset($orders_details))
                                @foreach($orders_details as $key => $value)
                                    <tr class="text-center">
                                        <td>{{$products[$value->product_id]}}</td>
                                        <td>{{$value->quantity}}</td>
                                        <td>{{number_format($value->money)}}</td>
                                        <td>{{number_format($value->total_money)}}</td>
                                    </tr>
                                @endforeach
                                    <tr>
                                        <th colspan="3" style="font-weight: 600; text-align: right">Tổng cộng:</th>
                                        <td class="text-center">{{number_format($total)}}</td>
                                    </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </form>
    </div>



@stop